Resources:
  test1:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      MemorySize: 512
      Handler: index.handler
      CodeUri: C:\Users\gstamatakis\IdeaProjects\wais\amplify\backend\function\test1\src
      Runtime: nodejs12.x
      Environment:
        Variables:
          REGION: eu-central-1
          API_WAISDYNAMODB_GRAPHQLAPIENDPOINTOUTPUT: https://c3ehvamjwfhgtmmlddwvn5umgi.appsync-api.eu-central-1.amazonaws.com/graphql
